#!/usr/bin/env bash
# Story 172 + 175 — config-dir usage-statusline snapshot installer.
#
# CC exposes live `rate_limits.{five_hour,seven_day}.{used_percentage,resets_at}`
# in exactly one place a process can observe it: the statusline command's stdin.
# The idle-limit-monitor polls a persisted copy of that data (Story 172 §3).
#
# Story 175: on opt-in we GENERATE a self-contained, WOW-owned snapshot
# statusline script in the user's CONFIG dir that (a) persists rate_limits to
# the state file and (b) delegates to the user's captured original statusline
# command, passing its stdout + exit through unchanged. The script resolves the
# config-dir target itself — it never writes a PROJECT .claude/settings.json.
#
# Modes:
#   --install [settings]   resolve the config-dir settings.json
#                          (${CLAUDE_CONFIG_DIR:-$HOME/.claude}/settings.json),
#                          generate the snapshot, point .statusLine.command at
#                          it, record the original. A [settings] arg is accepted
#                          only if it resolves to the config-dir settings; any
#                          other path is refused. Also repairs a prior buggy
#                          install found in the PROJECT .claude/settings.json.
#   --uninstall [settings] restore the recorded original (or remove .statusLine
#                          when the recorded original is empty) + remove the
#                          generated snapshot script.
#
# bash-3.2-safe. State path: ${WOW_USAGE_STATE_FILE:-$ROOT/implementations/.wow-process/five-hour-usage.json}.

set -u

SELF="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
GEN_BASENAME="wow-usage-statusline.sh"

config_dir() { printf '%s' "${CLAUDE_CONFIG_DIR:-$HOME/.claude}"; }
config_settings_path() { printf '%s/settings.json' "$(config_dir)"; }
generated_script_path() { printf '%s/%s' "$(config_dir)" "$GEN_BASENAME"; }

# Canonicalize a (possibly not-yet-existing) file path to an absolute path. The
# dirname must exist; the basename need not.
canon() {
  local p="$1" d b
  d=$(dirname "$p"); b=$(basename "$p")
  if [ -d "$d" ]; then printf '%s/%s' "$(cd "$d" && pwd)" "$b"; else printf '%s' "$p"; fi
}

# Emit a self-contained snapshot statusline script to $2 that bakes in the
# captured original command ($1). The persist logic is INLINED so the generated
# script never calls back into the plugin (survives plugin update/uninstall).
generate_snapshot_script() {
  local orig="$1" dest="$2" esc
  esc=$(printf '%s' "$orig" | sed "s/'/'\\\\''/g")
  {
    cat <<'HEADER'
#!/usr/bin/env bash
# GENERATED by claude-wow statusline-usage-persist.sh (Story 175). Do not edit.
# Snapshot of your original statusline command, captured at install time.
# Re-run `statusline-usage-persist.sh --install` to re-snapshot after changing
# your statusline; `--uninstall` restores the original and removes this file.
set -u
HEADER
    printf "WOW_STATUSLINE_ORIGINAL='%s'\n" "$esc"
    printf "WOW_STATUSLINE_FINGERPRINT='%s'\n" "$esc"
    cat <<'BODY'

resolve_root() {
  if [ -n "${WOW_ROOT:-}" ]; then printf '%s' "$WOW_ROOT"; return; fi
  if [ -n "${CLAUDE_PROJECT_DIR:-}" ]; then printf '%s' "$CLAUDE_PROJECT_DIR"; return; fi
  printf '%s' "$(pwd)"
}

state_file_path() {
  if [ -n "${WOW_USAGE_STATE_FILE:-}" ]; then
    printf '%s' "$WOW_USAGE_STATE_FILE"
  else
    printf '%s/implementations/.wow-process/five-hour-usage.json' "$(resolve_root)"
  fi
}

persist_usage() {
  local input="$1" state tmp present
  state="$(state_file_path)"
  present=$(printf '%s' "$input" | jq -r 'try (.rate_limits.five_hour.used_percentage) catch null' 2>/dev/null)
  if [ -z "$present" ] || [ "$present" = "null" ]; then return 0; fi
  mkdir -p "$(dirname "$state")" 2>/dev/null || true
  tmp="$state.tmp.$$"
  if printf '%s' "$input" | jq -c \
      --argjson ts "$(date -u +%s)" \
      '{five_hour: {used_percentage: .rate_limits.five_hour.used_percentage,
                    resets_at: .rate_limits.five_hour.resets_at},
        seven_day: {used_percentage: .rate_limits.seven_day.used_percentage,
                    resets_at: .rate_limits.seven_day.resets_at},
        captured_ts: $ts}' > "$tmp" 2>/dev/null; then
    mv "$tmp" "$state"
  else
    rm -f "$tmp" 2>/dev/null || true
  fi
}

input=$(cat)
persist_usage "$input"

# Empty original = the user had no statusline at install time. CC renders
# nothing when .statusLine is unset, so emitting nothing here is equivalent to
# the pre-install state (it does NOT blank a default — there is none).
if [ -z "$WOW_STATUSLINE_ORIGINAL" ]; then
  exit 0
fi
printf '%s' "$input" | eval "$WOW_STATUSLINE_ORIGINAL"
exit $?
BODY
  } > "$dest"
  chmod +x "$dest"
}

# True if a .statusLine.command string is one of our installs (current or
# legacy wrapper-as-command shape).
_is_wow_command() {
  case "$1" in
    *"$GEN_BASENAME"*|*statusline-usage-persist.sh*) return 0 ;;
    *) return 1 ;;
  esac
}

# Uninstall a WOW install from an arbitrary settings file: restore the recorded
# original command, or remove the .statusLine block entirely when the recorded
# original is empty (no blank wrapper left behind).
_uninstall_from() {
  local settings="$1" recorded tmp
  [ -f "$settings" ] || return 0
  recorded=$(jq -r '.statusLine.wowOriginalCommand // empty' "$settings" 2>/dev/null)
  tmp="$settings.tmp.$$"
  if [ -n "$recorded" ]; then
    jq --arg orig "$recorded" \
      '.statusLine.command = $orig
       | del(.statusLine.wowOriginalCommand)
       | del(.statusLine.wowStatuslineFingerprint)' \
      "$settings" > "$tmp" && mv "$tmp" "$settings"
  else
    jq 'del(.statusLine)' "$settings" > "$tmp" && mv "$tmp" "$settings"
  fi
}

# Repair a prior buggy install in the PROJECT .claude/settings.json (the
# wrong-scope case Story 175 fixes). Only touches a project settings that
# actually carries our install marker.
repair_project_install() {
  local proj="${CLAUDE_PROJECT_DIR:-$(pwd)}/.claude/settings.json"
  [ -f "$proj" ] || return 0
  local pcur
  pcur=$(jq -r '.statusLine.command // empty' "$proj" 2>/dev/null)
  [ -n "$pcur" ] || return 0
  if _is_wow_command "$pcur"; then
    _uninstall_from "$proj"
    echo "statusline-usage-persist: repaired prior install in project settings: $proj" >&2
  fi
}

install_wrapper() {
  local arg="${1:-}" settings gen current recorded orig tmp
  settings="$(config_settings_path)"
  mkdir -p "$(config_dir)" 2>/dev/null || true
  if [ -n "$arg" ]; then
    if [ "$(canon "$arg")" != "$(canon "$settings")" ]; then
      echo "statusline-usage-persist: refusing to install outside the config dir." >&2
      echo "  requested: $arg" >&2
      echo "  config-dir settings: $settings (pass no argument to use it)" >&2
      return 1
    fi
  fi
  [ -f "$settings" ] || printf '%s\n' '{}' > "$settings"
  gen="$(generated_script_path)"
  current=$(jq -r '.statusLine.command // empty' "$settings" 2>/dev/null)
  recorded=$(jq -r '.statusLine.wowOriginalCommand // empty' "$settings" 2>/dev/null)

  case "$current" in
    "$gen")
      # Already our generated script — idempotent no-op (do NOT re-capture,
      # which would clobber the recorded original with our own path). Still
      # sweep the project for a stale buggy install.
      repair_project_install
      return 0
      ;;
  esac
  if _is_wow_command "$current"; then
    # A legacy/relocated WOW install — the true original is the recorded one.
    orig="$recorded"
  else
    # A genuine user command (or empty).
    orig="$current"
  fi

  generate_snapshot_script "$orig" "$gen"
  tmp="$settings.tmp.$$"
  jq --arg cmd "$gen" --arg orig "$orig" \
    '.statusLine.type = "command"
     | .statusLine.command = $cmd
     | .statusLine.wowOriginalCommand = $orig
     | .statusLine.wowStatuslineFingerprint = $orig' \
    "$settings" > "$tmp" && mv "$tmp" "$settings"

  repair_project_install
}

uninstall_wrapper() {
  local arg="${1:-}" settings
  settings="$(config_settings_path)"
  if [ -n "$arg" ] && [ "$(canon "$arg")" != "$(canon "$settings")" ]; then
    echo "statusline-usage-persist: refusing to uninstall outside the config dir." >&2
    return 1
  fi
  [ -f "$settings" ] || { echo "statusline-usage-persist: settings file not found: $settings" >&2; return 1; }
  _uninstall_from "$settings"
  rm -f "$(generated_script_path)" 2>/dev/null || true
}

main() {
  case "${1:-}" in
    --install)   install_wrapper "${2:-}"; exit $? ;;
    --uninstall) uninstall_wrapper "${2:-}"; exit $? ;;
    *)
      echo "statusline-usage-persist: usage: $(basename "$0") --install|--uninstall [settings.json]" >&2
      exit 2
      ;;
  esac
}

main "$@"
